service: serverless-django
frameworkVersion: '3'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: serverless_django.wsgi.application
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1


functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

# functions:
#   get:
#     handler: rest/get.get
#     events:
#       - http:
#           path: /api/device/{id}
#           method: get
#           cors: true
#           integration: lambda
#           request:
#             paths:
#               id: true
