service: serverless-django
frameworkVersion: '3'

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: serverless_django.wsgi.application
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - httpApi:
          path: /api/devices/
          method: POST
      - httpApi:
          path: /api/devices/{proxy+}
          method: GET
      - httpApi:
          path: /api/models/
          method: POST
      # - http: 'ANY {proxy+}'